# Generated by Django 5.0.3 on 2024-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekendfoodfoot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletype',
            name='name',
            field=models.CharField(choices=[('COUPLE', 'Couple'), ('FAMILIAL', 'Familial'), ('INDIVIDUAL', 'Individuel'), ('VIP', 'VIP'), ('EXTRA_FAMILLE', 'Extra Famille'), ('FAMILIAL_MIXTE', 'Famille Mixte')], max_length=50, unique=True),
        ),
    ]
